---

- name: Uninstall ulauncher
  become: true
  ansible.builtin.package:
    name: ulauncher
    state: absent

- name: Remove unused dependencies
  become: true
  ansible.builtin.package:
    autoremove: true

...
