---

# Runs all dependencies


- name: Add build dependencies
  when: repo_check.stderr
  ansible.builtin.set_fact:
    ulauncher_global_dependencies: "{{ ulauncher_global_dependencies | combine(ulauncher_build_dependencies) }}"

- name: Install global dependencies
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ ulauncher_global_dependencies }}"

- name: Install Python dependencies
  ansible.builtin.pip:
    name: "{{ item }}"
  loop: "{{ ulauncher_pip_dependencies }}"

...
