---

# Runs all dependencies


- name: Install build dependencies
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ ulauncher_global_dependencies }}"

- name: Install Python dependencies
  ansible.builtin.pip:
    name: "{{ item }}"
  loop: "{{ ulauncher_pip_dependencies }}"

...
