---

- name: Add build dependencies
  ansible.builtin.set_fact:
    ulauncher_global_dependencies: "{{ ulauncher_global_dependencies + ulauncher_build_dependencies }}"

- name: Add epel repo
  become: true
  when: ansible_os_family == "RedHat"
  ansible.builtin.dnf:
    name: epel-release
    state: present
    update_cache: true

- name: Install global dependencies
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ ulauncher_global_dependencies }}"

- name: Install Python dependencies
  ansible.builtin.pip:
    name: "{{ item }}"
  loop: "{{ ulauncher_pip_dependencies }}"

...
