---

- name: Enable universe repository
  become: true
  ansible.builtin.deb822_repository:
    name: ubuntu
    types: [deb]
    uris: ["http://archive.ubuntu.com/ubuntu"]
    suites:
      - "{{ ansible_facts.distribution_release }}"
      - "{{ ansible_facts.distribution_release }}-updates"
      - "{{ ansible_facts.distribution_release }}-security"
      - "{{ ansible_facts.distribution_release }}-backports"
    components: [main, universe]
    signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg
    state: present
    install_python_debian: true

- name: Add ulauncher ppa
  become: true
  ansible.builtin.deb822_repository:
    name: ulauncher
    types: [deb]
    uris: ["http://ppa.launchpad.net/agornostal/ulauncher/ubuntu"]
    suites: "{{ ansible_facts.distribution_release | lower }}"
    components: [main]
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xFAF1020699503176"
    state: present
    install_python_debian: true
  register: ulauncher_ppa
  retries: 5
  delay: 5
  until: ulauncher_ppa is succeeded

- name: Install ulauncher
  become: true
  ansible.builtin.apt:
    name: ulauncher
    state: present
    update_cache: true

...
