---

- name: Add Ulauncher apt repository
  become: true
  ansible.builtin.deb822_repository:
    name: ulauncher
    enabled: true
    allow_insecure: true
    allow_weak: true
    types: [deb]
    uris: [http://ppa.launchpad.net/agornostal/ulauncher/ubuntu]
    suites: "{{ ulauncher_debian_to_ubuntu_map[ansible_facts.distribution_release | lower] }}"
    components: [main]
    allow_downgrade_to_insecure: true
    trusted: true
    # Note obsolete when `trusted: true`
    # signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xFAF1020699503176"
    install_python_debian: true
  register: ulauncher_ppa
  retries: 5
  delay: 5
  until: ulauncher_ppa is succeeded

- name: Install ulauncher
  become: true
  ansible.builtin.apt:
    name: ulauncher
    state: present
    update_cache: true

...
