---

# Tasks to install ulauncher


- name: Gather package facts
  ansible.builtin.package_facts:

- name: Decide install method
  when: "'ulauncher' not in ansible_facts.packages"
  block:
    - name: Check if ulauncher is available in distro repository
      ansible.builtin.shell: 
        cmd: "{{ package_search[ansible_os_family] }} ulauncher || true"
      register: repo_check
      changed_when: false

    - name: Include dependencies
      ansible.builtin.include_tasks:
        file: dependencies.yml

    - name: Install from distro repo
      when: not repo_check.stderr
      become: true
      ansible.builtin.package:
        name: ulauncher
        state: present

    - name: Include Ulauncher installation
      when: repo_check.stderr
      ansible.builtin.include_tasks:
        file: present_install.yml

- name: Include configuration
  ansible.builtin.include_tasks:
    file: present_configure.yml

- name: Ensure ulauncher service is enabled
  ansible.builtin.systemd:
    name: ulauncher.service
    enabled: true
    scope: user

...
