---

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Decide install method
  when: "'ulauncher' not in ansible_facts.packages"
  block:
    - name: Installation Ulauncher for debian based distros
      when: ansible_os_family == "Debian"
      ansible.builtin.include_tasks:
        file: "install_{{ ansible_distribution | lower }}.yml"

    - name: Installation Ulauncher for redhat based distros
      when: ansible_os_family == "RedHat"
      ansible.builtin.include_tasks:
        file: "install_{{ ansible_os_family | lower }}.yml"

- name: Ensure ulauncher service is enabled
  ansible.builtin.systemd_service:
    name: ulauncher.service
    enabled: true
    scope: "user"

...
