---

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Install Ulauncher on based on distro
  when: "'ulauncher' not in ansible_facts.packages"
  ansible.builtin.include_tasks:
    file: "install_{{ ulauncher_install_matrix[ansible_facts.distribution | lower] }}.yml"

...
