---

# tasks to install ansible-role-template
# INFO larger roles should only use **include_tasks** here


# INFO This task may be osbolete for your use-case
- name: Gather package facts
  ansible.builtin.package_facts:

- name: Clone ulauncher repo from github
  ansible.builtin.git:
    repo: "https://github.com/Ulauncher/Ulauncher.git"
    dest: "~/Ulauncher"
    single_branch: true
    version: "5.15.7"
    depth: 1
  register: git_result
  until: git_result is succeeded
  retries: 5
  delay: 10

- name: Install build dependencies
  become: true
  ansible.builtin.dnf:
    name:
      - pip
      - wmctrl
      - yarnpkg
      - rsync
      - rpm-build
      - keybinder3
      - python3-gobject
      - python3-dbus
      - python3-distutils-extra
      - python3-pyxdg
      - python3-inotify
    state: present

- name: Install Python packages in the virtual environment
  ansible.builtin.pip:
    name:
      - wheel
      - Levenshtein
      - websocket

- name: Create a Python virtual environment
  ansible.builtin.command:
    cmd: python3.9 -m venv --system-site-packages ~/python_env/ulauncher_build_env/
  args:
    creates: ~/python_env/ulauncher_build_env/bin/activate

- name: Build RPM package
  ansible.builtin.command:
    cmd: ./ul build-preferences
  args:
    chdir: "~/Ulauncher"

# TODO broken in original repo - use fork to fix
- name: Build RPM package
  ansible.builtin.command:
    cmd: ./ul build-rpm 5.15.7 alma9.4
  args:
    chdir: "~/Ulauncher"

- name: Install Ulauncher
  ansible.builtin.dnf:
    name: /tmp/ulauncher_5.15.7_alma9.4.rpm
    state: present

- name: Remove osbolete pip packages
  ansible.builtin.pip:
    name:
      - websocket
    state: absent

- name: Remove build dependencies
  become: true
  ansible.builtin.dnf:
    name: 
      - yarnpkg
      - rsync
      - rpm-build
      - python3-distutils-extra
      - python3-pyxdg
      - python3-inotify
    state: absent

...
