---

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Test installed global dependencies
  loop: "{{ ulauncher_global_dependencies }}"
  when: ansible_os_family == "RedHat"
  ansible.builtin.assert:
    that:
      - item in ansible_facts.packages
    fail_msg: "Required package '{{ item }}' is missing."
    quiet: true

- name: Test installed ulauncher
  ansible.builtin.assert:
    that:
      - "'ulauncher' in ansible_facts.packages"
    fail_msg: "Ulauncher' is not installed."
    quiet: true

...
