---

# Variables for ansible-role-template

ulauncher_settings:
  "blacklisted-desktop-dirs": "/usr/share/locale:/usr/share/app-install:/usr/share/kservices5:/usr/share/fk5:/usr/share/kservicetypes5:/usr/share/applications/screensavers:/usr/share/kde4:/usr/share/mimelnk"
  "clear-previous-query": true
  "disable-desktop-filters": false
  "grab-mouse-pointer": false
  "hotkey-show-app": "<Alt>space"
  "render-on-screen": "mouse-pointer-monitor"
  "show-indicator-icon": true
  "show-recent-apps": "10"
  "terminal-command": ""
  "theme-name": "Omni"

ulauncher_extensions:
  "com.github.friday.ulauncher-gnome-settings":
    id: "com.github.friday.ulauncher-gnome-settings"
    url: "https://github.com/friday/ulauncher-gnome-settings"

  "com.github.zensoup.ulauncher-unicode":
    id: "com.github.zensoup.ulauncher-unicode"
    url: "https://github.com/zensoup/ulauncher-unicode"

  "com.github.manahter.ulauncher-translate":
    id: "com.github.manahter.ulauncher-translate"
    url: "https://github.com/manahter/ulauncher-translate"

  "com.github.ulauncher.ulauncher-kill":
    id: "com.github.ulauncher.ulauncher-kill"
    url: "https://github.com/Ulauncher/ulauncher-kill"

ulauncher_github_repo_theme:
  - name: "ulauncher omni theme"
    repo_url: "https://github.com/philnewm/ulauncher_theme.git"
    branch: "main"
    install_cmd: ""
    download_dir: "{{ (ansible_env.HOME, '.config', 'ulauncher', 'user-themes', 'omni') | ansible.builtin.path_join }}"
    install_dir: ""

gdm_config_file:
  "CentOS": "/etc/gdm/custom.conf"
  "AlmaLinux": "/etc/gdm/custom.conf"
  "Rocky": "/etc/gdm/custom.conf"
  "Ubuntu": "/etc/gdm3/custom.conf"
  "Debian": "/etc/gdm3/daemon.conf"

...
